services:
  squashtm-pg:
    container_name: squashtm-pg
    environment:
      POSTGRES_DB: squashtm
      POSTGRES_USER: squashtm
      POSTGRES_PASSWORD: MustB3Ch4ng3d
    image: postgres:17
    ports:
      - 5432:5432

  squashtm:
    container_name: squashtm
    image: squashtest/squash:13.0.1
    depends_on:
      - squashtm-pg
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://squashtm-pg:5432/squashtm
      SPRING_DATASOURCE_USERNAME: squashtm
      SPRING_DATASOURCE_PASSWORD: MustB3Ch4ng3d
    ports:
      - 8090:8080
    volumes:
      - squashtm-logs:/opt/squash-tm/logs

volumes:
  squashtm-logs:
